### ISSUE TITLE
Open Recent Apps module can't be completed.

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#14]
Lesson 5, Module 3, Open Recent Apps can't be completed. Upon returning to the application, TTS is abruptly interrupted leaving the user stranded.

https://user-images.githubusercontent.com/60597159/167848493-e6e94704-1bee-42eb-87a2-f82006a48572.mp4

**Comment by jaiclapp** [comment]
Module originally required the user to enter another app from the recent apps menu, before returning to the tutorial. This was not clear enough. Module was changed so the user only needs to open the recent apps menu, not go into another app for the module to progress. 

Change was pushed to team1/sprint2 branch.

![image](https://user-images.githubusercontent.com/80311461/168413957-c40b1124-c364-4f3b-b8c7-7b926a1dba1e.png)

New version of module uses a WindowFocusChangeListener instead of previously used LifecycleEventListener.
