### ISSUE TITLE
Lesson 3 Module 2 Revamp

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#43]
This module has a few issues that need to be addressed.

* [x] Why do I have to listen to the entire peter picked a whatever before hearing the instructions
* [x] The instructions aren't all that clear on the goal
* [x] The module indicates to search for a button "finish lesson", yet to finish the module you have to find "finish module", and it isn't even a button

Reference:
https://www.youtube.com/watch?v=vm5zZ1cjz5A&t=12s

**Comment by Chokss54** [comment]
revamp module 3 completed

**Comment by Andre-Pham** [comment]
These were not addressed. I'm not sure why you marked it completed thinking that no one would notice.

**Comment by Chokss54** [comment]
I did not mark it complete and didn't want anyone to notice. Perhaps I have revamped the module from what initially we wanted which is just to teach paragraph reading modes to make lessons for all types of text reading modes for the users to understand and be familiar with switching modes. And the issues stated did not happen when Matt reviewed using his android phone. So now I might need to find more people who have android phones to test out. And for the button issue. We only can put it as a text listener because it is under text reading mode... but in the TTS intro told them that it is a button so that they know they have to double tap it to continue the module
