### ISSUE TITLE
Locked Lessons and Modules Don’t Provide Feedback

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#90]
Make it so that when locked lessons/modules are interacted with, a message is played indicating to complete the previous lesson/module first. Make it informative, don't just say something bland like "lesson locked".

**Comment by mcrossman** [comment]
Using a click listener can make TalkBack say "Double tap to activate" when focusing on locked modules, which would encourage users to tap them which would be confusing.

**Comment by mingxuan-fu** [comment]
Was going to do something fancy using accessibility delegate before deciding just adding a dynamic content description is much easier. Talkback reads out the content description instead of the title and subtitle, currently this is not converted to string resources as it involves some template strings that I'm not quite sure how best to convert without generating tons of tiny text fragments. Also fixed talkback reading 'double tap to activate' on locked lesson/module.
